package com.qding.bigdata.ds.dao;

import com.qding.bigdata.ds.model.DIMWare;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DIMWareDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_ware
     *
     * @mbggenerated Thu Jan 17 10:58:41 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_ware
     *
     * @mbggenerated Thu Jan 17 10:58:41 CST 2019
     */
    int insert(DIMWare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_ware
     *
     * @mbggenerated Thu Jan 17 10:58:41 CST 2019
     */
    int insertSelective(DIMWare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_ware
     *
     * @mbggenerated Thu Jan 17 10:58:41 CST 2019
     */
    DIMWare selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_ware
     *
     * @mbggenerated Thu Jan 17 10:58:41 CST 2019
     */
    int updateByPrimaryKeySelective(DIMWare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_ware
     *
     * @mbggenerated Thu Jan 17 10:58:41 CST 2019
     */
    int updateByPrimaryKey(DIMWare record);

    List<DIMWare> listByIDs(@Param("ids") String ids);
}